### ISSUE TITLE
任意基于unet的模型都兼容吗？

### ISSUE THREAD

**Issue by CanvaChen** [360CVGroup/FancyVideo#15]
base model是否可以替换成任意一个基于unet的？

**Comment by MaAo** [comment]
> base model是否可以替换成任意一个基于unet的？

Thanks to your interest in our work, the bottom models of the sd 1.5 series are compatible.

**Comment by AA-Developer** [comment]
@CanvaChen  The model build works on version sd 1.5 only.
I don't know if it will do another generation for XL version.
